# Generated by Django 6.0.1 on 2026-01-24 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The quote text')),
                ('author', models.CharField(blank=True, help_text='Author of the quote', max_length=255)),
                ('category', models.CharField(choices=[('motivation', 'Motivation'), ('success', 'Success'), ('perseverance', 'Perseverance'), ('courage', 'Courage'), ('inspiration', 'Inspiration'), ('growth', 'Growth'), ('wisdom', 'Wisdom')], default='motivation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Include in daily send')),
            ],
            options={
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_time', models.TimeField(default='08:00', help_text='Preferred time to receive quotes (HH:MM format)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SentQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_instances', to='motivational_quotes.quote')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motivational_quotes.subscription')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
